import dimension_theory_depth_commutative_rings_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace dimension_theory_depth_commutative_rings_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end dimension_theory_depth_commutative_rings_theorem_canonical_lane_mathlib
end HautevilleHouse
